repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: detect-private-key
  - repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
    -   id: fmt
    -   id: cargo-check
    -   id: clippy
#   - repo: https://github.com/crate-ci/typos
#     rev: v1.21.0
#     hooks:
#     - id: typos
#       stages: [commit]
  - repo: https://github.com/crate-ci/committed
    rev: v1.0.20
    hooks:
    - id: committed
      stages: [commit-msg]
exclude: '.vscode'
default_stages:
  - 'pre-commit'
  - 'pre-push'
