[package]
name = "alertsinua-tui"
version = "0.1.1"
authors = ["voznik <mrvoznik@gmail.com>"]
license = "MIT"
edition = "2021"

[dependencies]
anyhow = "1.0"
async-trait = "0.1.80"
arrayvec = "0.7.4"
either = "1.11"
strum = "0.26"
const-default = "1.0"
crossterm = { version = "0.27.0", features = ["event-stream"] }
futures = "0.3"
futures-util = "0.3"
ratatui = "0.26.2"
sqlx = { version = "0.7.4", features = ["sqlite", "runtime-tokio-native-tls"] }
tokio = { version = "1.35.1", features = ["full"] }
tracing = "0.1"
tracing-appender = "0.2"
tracing-subscriber = "0.3"
csv = "1.3.0"
serde = { version = "1.0", features = ["derive"] }
wkt = "0.10.3"
geo = "0.28.0"
delegate = "0.12.0"
getset = "0.1"
# geozero = { version = "0.12.0", features = ["with-csv", "with-geo"] }
