[package]
name = "alertsinua-tui"
version = "0.1.1"
authors = ["voznik <mrvoznik@gmail.com>"]
license = "MIT"
edition = "2021"

[dependencies]
anyhow = "1.0"
arrayvec = "0.7.4"
async-trait = "0.1.80"
chrono = "0.4"
const-default = "1.0"
crossterm = { version = "0.27.0", features = ["event-stream"] }
csv = "1.3.0"
color-eyre = "0.6"
delegate = "0.12.0"
dotenv = "0.15"
either = "1.11"
futures = "0.3"
futures-util = "0.3"
geo = "0.28.0"
getset = "0.1"
lazy_static = "1.4.0"
ratatui = "0.26.2"
reqwest = { version = "0.12", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
sqlx = { version = "0.7.4", features = ["sqlite", "runtime-tokio-native-tls"] }
strum = "0.26"
tokio = { version = "1.35.1", features = ["full"] }
tokio-util = "0.7.9"
tracing = "0.1"
tracing-error = "0.2"
tracing-appender = "0.2"
tracing-subscriber = { version = "0.3", features = ["env-filter", "serde"] }
wkt = "0.10.3"
# geozero = { version = "0.12.0", features = ["with-csv", "with-geo"] }
