[package]
name = "alertsinua-tui"
version = "0.1.0"
authors = ["Vadym Parakonnyi <v.parakonnyi@gmail.com>"]
license = "MIT"
edition = "2021"

[dependencies]
anyhow = "1.0"
crossterm = { version = "0.27.0", features = ["event-stream"] }
futures = "0.3.30"
ratatui = "0.26.0"
sqlx = { version = "0.7.4", features = ["sqlite", "runtime-tokio-native-tls"] }
tokio = { version = "1.35.1", features = ["full"] }
tracing = "0.1"
tracing-appender = "0.2"
tracing-subscriber = "0.3"
csv = "1.3.0"
serde = { version = "1.0", features = ["derive"] }
wkt = "0.10.3"
geo = "0.28.0"
geo-types = "0.7.13"
geozero = { version = "0.12.0", features = ["with-csv", "with-geo"] }
