[package]
name = "ralertsinua-models"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
color-eyre = "0.6"
serde = { version = "1.0.198", features = ["derive"] }
serde_json = "1.0.116"
strum = "0.26"
strum_macros = "0.26"
sqlx = { version = "0.7.4", features = [] }
thiserror = "1.0"